# Generated by Django 5.0.3 on 2024-04-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=256, null=True)),
                ('theme', models.CharField(blank=True, max_length=256, null=True)),
                ('genretype', models.CharField(blank=True, max_length=256, null=True)),
                ('genre', models.CharField(blank=True, max_length=256, null=True)),
                ('author', models.CharField(blank=True, max_length=256, null=True)),
                ('creationyear', models.CharField(blank=True, max_length=256, null=True)),
                ('composer', models.CharField(blank=True, max_length=256, null=True)),
                ('fullname', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
